apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shop-ingress-{{ EVENT_NAME }}
  labels:
    event: {{ EVENT_NAME }}
spec:
  tls:
    - hosts:
        - {{ EVENT_NAME }}.cloudcoin.us-south.containers.appdomain.cloud
      secretName: cloudcoin
  rules:
  - host: {{ EVENT_NAME }}.cloudcoin.us-south.containers.appdomain.cloud
    http:
      paths:
      - backend:
          serviceName: shop-backend-{{ EVENT_NAME }}
          servicePort: 3030