apiVersion: v1
kind: Service
metadata:
  name: orderer0-{{ EVENT_NAME }}
  labels:
    app: orderer0
    event: {{ EVENT_NAME }}
spec:
  type: ClusterIP
  ports:
    - port: 7050
      protocol: TCP
  selector:
    app: orderer0
    event: {{ EVENT_NAME }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: orderer0-deployment-{{ EVENT_NAME }}
  labels:
    app: orderer0
    event: {{ EVENT_NAME }}
spec:
  template:
    metadata:
      labels:
        app: orderer0
        event: {{ EVENT_NAME }}
    spec:
      containers:
      - image: hyperledger/fabric-orderer:1.2.0
        imagePullPolicy: Always
        workingDir: /orderer
        command: ["sh", "-c", "sleep 5 && while [ ! -f /orderer/bootstrapped ]; do echo Waiting for bootstrap; sleep 1; done; orderer"]
        name: orderer0
        ports:
        - containerPort: 7050
          name: orderer0
        env:
          - name: ORDERER_GENERAL_LOGLEVEL
            value: "debug"
          - name: ORDERER_GENERAL_LISTENADDRESS
            value: "0.0.0.0"
          - name: ORDERER_GENERAL_GENESISMETHOD
            value: "file"
          - name: ORDERER_GENERAL_GENESISFILE
            value: "/orderer/crypto/genesis.block"
          - name: ORDERER_GENERAL_LOCALMSPID
            value: "OrdererMSP"
          - name: ORDERER_GENERAL_LOCALMSPDIR
            value: "/orderer/crypto/msp"
          - name: ORDERER_GENERAL_TLS_ENABLED
            value: "false"
          # - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          #   value: "/orderer/crypto/tls/server.key"
          # - name: ORDERER_GENERAL_TLS_CERTIFICATE
          #   value: "/orderer/crypto/tls/server.crt"
          # - name: ORDERER_GENERAL_TLS_ROOTCAS
          #   value: "[/orderer/crypto/tls/ca.crt]"
        volumeMounts:
          - name: orderer0-storage
            mountPath: /var/hyperledger/production
            subPath: orderer0-{{ EVENT_NAME }}
          - name: shared-artifacts-storage
            mountPath: /orderer
            subPath: orderer0-config-{{ EVENT_NAME }}
      volumes:
        - name: orderer0-storage
          persistentVolumeClaim:
            claimName: peer-claim
        - name: shared-artifacts-storage
          persistentVolumeClaim:
            claimName: shared-artifacts-claim
