apiVersion: v1
kind: Service
metadata:
  name: rabbitclient-api-{{ EVENT_NAME }}
  labels:
    app: rabbitclient-api
    event: {{ EVENT_NAME }}
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: rabbitclient-api
    event: {{ EVENT_NAME }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbitclient-api-deployment-{{ EVENT_NAME }}
  labels:
    app: rabbitclient-api
    event: {{ EVENT_NAME }}
spec:
  template:
    metadata:
      labels:
        app: rabbitclient-api
        event: {{ EVENT_NAME }}
    spec:
      containers:
      - image: anthonyamanse/kubecon-rabbitclient-api:event
        imagePullPolicy: Always
        name: rabbitclient-api
        ports:
        - containerPort: 3000
        env:
          - name: SECRETSDIR
            value: "/host/var/run/secrets"
          - name: PORT
            value: "3000"
        volumeMounts:
          - name: secret-volume
            mountPath: /host/var/run/secrets
      volumes:
        - name: secret-volume
          secret:
            secretName: secret-files-{{ EVENT_NAME }}
            items:
              - key: config.json
                path: config
              - key: channel.tx
                path: channel
