apiVersion: v1
kind: Service
metadata:
  name: shop-backend-{{ EVENT_NAME }}
  labels:
    app: shop-backend
    event: {{ EVENT_NAME }}
spec:
  type: LoadBalancer
  ports:
    - port: 3030
  selector:
    app: shop-backend
    event: {{ EVENT_NAME }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shop-backend-deployment-{{ EVENT_NAME }}
  labels:
    app: shop-backend
    event: {{ EVENT_NAME }}
spec:
  template:
    metadata:
      labels:
        app: shop-backend
        event: {{ EVENT_NAME }}
    spec:
      containers:
      - image: anthonyamanse/kubecon-backend:event
        imagePullPolicy: Always
        name: shop-backend
        ports:
        - containerPort: 3030
        env:
          - name: ORGID
            value: "org.ShopOrg"
          - name: DOCKER_SOCKET_PATH
            value: "/host/var/run/docker.sock"
          - name: DOCKER_CCENV_IMAGE
            value: "hyperledger/fabric-ccenv:1.2.0"
          - name: SECRETSDIR
            value: "/host/var/run/secrets"
          - name: RABBITMQQUEUE
            value: "seller_queue-{{ EVENT_NAME }}"
          - name: SOCKETPORT
            value: "3030"
          - name: MESSAGEEXPIRY
            value: "400"
          - name: EVENTEMITTER
            value: "true"
          - name: SCALECLIENT
            value: "1"
        volumeMounts:
          - name: dockersocket
            mountPath: /host/var/run/docker.sock
          - name: secret-volume
            mountPath: /host/var/run/secrets
      volumes:
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
        - name: secret-volume
          secret:
            secretName: secret-files-{{ EVENT_NAME }}
            items:
              - key: config.json
                path: config
              - key: channel.tx
                path: channel
