apiVersion: v1
kind: Service
metadata:
  name: shop-statedb-{{ EVENT_NAME }}
  labels:
    app: shop-statedb
    event: {{ EVENT_NAME }}
spec:
  type: ClusterIP
  ports:
    - port: 5984
  selector:
    app: shop-statedb
    event: {{ EVENT_NAME }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shop-statedb-deployment-{{ EVENT_NAME }}
  labels:
    app: shop-statedb
    event: {{ EVENT_NAME }}
spec:
  template:
    metadata:
      labels:
        app: shop-statedb
        event: {{ EVENT_NAME }}
    spec:
      containers:
      - image: ishangulhane/fabric-couchdb
        imagePullPolicy: Always
        name: shop-statedb
        ports:
        - containerPort: 5984
        volumeMounts:
        - name: shop-datastore-storage
          mountPath: /opt/couchdb/data
          subPath: shop-statedb-{{ EVENT_NAME }}
      volumes:
      - name: shop-datastore-storage
        persistentVolumeClaim:
          claimName: couchdb-claim
