apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-artifacts-volume
spec:
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: shared-artifacts-claim
  nfs:
    server: "fsf-dal1301g-fz.adn.networklayer.com"
    path: "/IBM02SEV1323471_1607/data01"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "" # Comment this line to use dynamic provisioning (paid)
  name: shared-artifacts-claim
  labels:
    app: shared-artifacts-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
